
CUDA_VISIBLE_DEVICES=0,1 accelerate launch train_single_v3.py \
 --pretrained_model_name_or_path="checkpoints/SVD" \
 --output_dir="checkpoints/Animation_600video_clothes_v16" \
 --data_root_path="animation_data" \
 --data_path="animation_data/video_path_512_256.txt" \
 --dataset_width=256 \
 --dataset_height=512 \
 --validation_image_folder="/data/muxiangyu/pythonPrograms/StableAnimator/validation/validation_512_256/centered_heads" \
 --validation_control_folder="/data/muxiangyu/pythonPrograms/StableAnimator/validation/validation_512_256/pose_wo_head" \
 --validation_clothes_folder="/data/muxiangyu/pythonPrograms/StableAnimator/validation/validation_512_256/clothes_white_complete" \
 --validation_image="/data/muxiangyu/pythonPrograms/StableAnimator/validation/validation_512_256/centered_heads/frame_001.png" \
 --validation_cloth_image="/data/muxiangyu/pythonPrograms/StableAnimator/validation/validation_512_256/clothes_white_complete/frame_001.png" \
 --validation_face_pose='/data/muxiangyu/pythonPrograms/StableAnimator/validation/validation_512_256/pose_head_new/frame_001.png' \
 --num_workers=1 \
 --lr_warmup_steps=500 \
 --sample_n_frames=8 \
 --learning_rate=1e-5 \
 --per_gpu_batch_size=1 \
 --num_train_epochs=200 \
 --mixed_precision="fp16" \
 --gradient_accumulation_steps=1 \
 --checkpointing_steps=1500 \
 --validation_steps=600 \
 --gradient_checkpointing \
 --checkpoints_total_limit=5 \
 --resume_from_checkpoint="latest" > train_single.log 2>&1